import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts/index';
import './globals.css';

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`text-xl ${inter.className}`}>{children}</body>
        </html>
    );
}
